services:
  db:
    image: mysql:5.7
    container_name: isla_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"  # opcional si quieres acceder a MySQL desde host
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: isla_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db

  web:
    build:
      context: ./apache-php
    container_name: isla_web
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./apache-php:/var/www/html/apache-php
    depends_on:
      - db
    command: ["/var/www/html/apache-php/wait-for-db.sh"]

volumes:
  db_data:
